security:
    enable_authenticator_manager: true

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    password_hashers:
        App\Entity\User:
            algorithm: auto

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            logout:
                path: admin_logout
                target: admin_login

    access_control:
        # Разрешить доступ к логину всем
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }

        # Закрыть всё остальное под /admin только для авторизованных
        - { path: ^/admin, roles: ROLE_ADMIN }
