<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260915120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'game_price: ежедневные снимки цен игр из Steam (RU); '
            . 'steam_price_import_cursor: курсор пачечного импорта цен';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE game_price (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                game_id INT NOT NULL,
                date DATE NOT NULL,
                price_kopecks INT DEFAULT NULL,
                currency VARCHAR(3) NOT NULL,
                is_free BOOLEAN NOT NULL,
                is_available_in_russia BOOLEAN NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_GAME_PRICE_GAME ON game_price (game_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_GAME_PRICE_GAME_DATE ON game_price (game_id, date)');
        $this->addSql(
            'ALTER TABLE game_price ADD CONSTRAINT FK_GAME_PRICE_GAME '
            . 'FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE',
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE steam_price_import_cursor (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                last_steam_game_id INT NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE steam_price_import_cursor');
        $this->addSql('ALTER TABLE game_price DROP CONSTRAINT FK_GAME_PRICE_GAME');
        $this->addSql('DROP TABLE game_price');
    }
}
