<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260812150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'game_reaction/game_favorite/game_status: лайк/дизлайк, избранное и статус прохождения игры';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE game_reaction (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                game_id INT NOT NULL,
                user_id INT NOT NULL,
                type VARCHAR(10) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql(
            'CREATE UNIQUE INDEX UNIQ_GAME_REACTION_GAME_USER ON game_reaction (game_id, user_id)',
        );
        $this->addSql('CREATE INDEX IDX_GAME_REACTION_USER ON game_reaction (user_id)');
        $this->addSql(
            'ALTER TABLE game_reaction ADD CONSTRAINT FK_GAME_REACTION_GAME '
            . 'FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE',
        );
        $this->addSql(
            'ALTER TABLE game_reaction ADD CONSTRAINT FK_GAME_REACTION_USER '
            . 'FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE',
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE game_favorite (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                game_id INT NOT NULL,
                user_id INT NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql(
            'CREATE UNIQUE INDEX UNIQ_GAME_FAVORITE_GAME_USER ON game_favorite (game_id, user_id)',
        );
        $this->addSql('CREATE INDEX IDX_GAME_FAVORITE_USER ON game_favorite (user_id)');
        $this->addSql(
            'ALTER TABLE game_favorite ADD CONSTRAINT FK_GAME_FAVORITE_GAME '
            . 'FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE',
        );
        $this->addSql(
            'ALTER TABLE game_favorite ADD CONSTRAINT FK_GAME_FAVORITE_USER '
            . 'FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE',
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE game_status (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                game_id INT NOT NULL,
                user_id INT NOT NULL,
                status VARCHAR(15) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql(
            'CREATE UNIQUE INDEX UNIQ_GAME_STATUS_GAME_USER ON game_status (game_id, user_id)',
        );
        $this->addSql('CREATE INDEX IDX_GAME_STATUS_USER ON game_status (user_id)');
        $this->addSql(
            'ALTER TABLE game_status ADD CONSTRAINT FK_GAME_STATUS_GAME '
            . 'FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE',
        );
        $this->addSql(
            'ALTER TABLE game_status ADD CONSTRAINT FK_GAME_STATUS_USER '
            . 'FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE',
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE game_reaction');
        $this->addSql('DROP TABLE game_favorite');
        $this->addSql('DROP TABLE game_status');
    }
}
