<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260812170000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'user_follow: подписки пользователей друг на друга';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE user_follow (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                follower_id INT NOT NULL,
                followed_id INT NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql(
            'CREATE UNIQUE INDEX UNIQ_USER_FOLLOW_FOLLOWER_FOLLOWED ON user_follow (follower_id, followed_id)',
        );
        $this->addSql('CREATE INDEX IDX_USER_FOLLOW_FOLLOWER ON user_follow (follower_id)');
        $this->addSql('CREATE INDEX IDX_USER_FOLLOW_FOLLOWED ON user_follow (followed_id)');
        $this->addSql(
            'ALTER TABLE user_follow ADD CONSTRAINT FK_USER_FOLLOW_FOLLOWER '
            . 'FOREIGN KEY (follower_id) REFERENCES "user" (id) ON DELETE CASCADE',
        );
        $this->addSql(
            'ALTER TABLE user_follow ADD CONSTRAINT FK_USER_FOLLOW_FOLLOWED '
            . 'FOREIGN KEY (followed_id) REFERENCES "user" (id) ON DELETE CASCADE',
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE user_follow');
    }
}
