<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260915120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'steam_game_prices: ежедневные снимки цен игр из Steam (RU); '
            . 'steam_price_import_cursor: курсор пачечного импорта цен';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE steam_game_prices (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                game_id INT NOT NULL,
                date DATE NOT NULL,
                price_kopecks INT DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_STEAM_GAME_PRICES_GAME ON steam_game_prices (game_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_STEAM_GAME_PRICES_GAME_DATE ON steam_game_prices (game_id, date)');
        $this->addSql(
            'ALTER TABLE steam_game_prices ADD CONSTRAINT FK_STEAM_GAME_PRICES_GAME '
            . 'FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE',
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE steam_price_import_cursor (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                last_steam_game_id INT NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE steam_price_import_cursor');
        $this->addSql('ALTER TABLE steam_game_prices DROP CONSTRAINT FK_STEAM_GAME_PRICES_GAME');
        $this->addSql('DROP TABLE steam_game_prices');
    }
}
