<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260817110000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'user_report: отчёты пользователей о проблемах (сайт/приложение/игра DIE//AGAIN)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE user_report (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                type SMALLINT NOT NULL,
                comment TEXT NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_USER_REPORT_TYPE ON user_report (type)');
        $this->addSql('CREATE INDEX IDX_USER_REPORT_CREATED_AT ON user_report (created_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE user_report');
    }
}
