<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260811120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'score_die_again: таблица лидеров игры DIE//AGAIN (ник, уровень, время выживания, убийства)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE score_die_again (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                nickname VARCHAR(50) NOT NULL,
                level INT NOT NULL,
                survived_seconds INT NOT NULL,
                kills INT NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE score_die_again');
    }
}
