<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260810140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'user: nickname/avatar_url/last_login_at; cron: справочник обнаруженных кронов; '
            . 'dlc (+dlc_developer/publisher/genre/platform), steam_game.game_id nullable, steam_game.dlc_id; '
            . 'take, take_comment, take_reaction (тэйки об играх, комментарии, лайк/дизлайк)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            ALTER TABLE "user"
                ADD nickname VARCHAR(50) DEFAULT NULL,
                ADD avatar_url VARCHAR(255) DEFAULT NULL,
                ADD last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL
        SQL);

        $this->addSql(<<<'SQL'
            CREATE TABLE cron (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                command VARCHAR(255) NOT NULL,
                color VARCHAR(7) DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CRON_COMMAND ON cron (command)');

        $this->addSql(<<<'SQL'
            CREATE TABLE dlc (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                game_id INT DEFAULT NULL,
                name VARCHAR(255) NOT NULL,
                slug VARCHAR(255) NOT NULL,
                description TEXT DEFAULT NULL,
                release_date DATE DEFAULT NULL,
                cover_image_path VARCHAR(500) DEFAULT NULL,
                screenshot_urls JSON DEFAULT NULL,
                pending_base_game_steam_app_id INT DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AD6CAEA7989D9B62 ON dlc (slug)');
        $this->addSql('CREATE INDEX IDX_AD6CAEA7E48FD905 ON dlc (game_id)');
        $this->addSql(
            'ALTER TABLE dlc ADD CONSTRAINT FK_AD6CAEA7E48FD905 '
            . 'FOREIGN KEY (game_id) REFERENCES game (id) NOT DEFERRABLE INITIALLY IMMEDIATE',
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE dlc_developer (
                dlc_id INT NOT NULL,
                developer_id INT NOT NULL,
                PRIMARY KEY(dlc_id, developer_id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_EEBD650BCEF6326C ON dlc_developer (dlc_id)');
        $this->addSql('CREATE INDEX IDX_EEBD650B64DD9267 ON dlc_developer (developer_id)');
        $this->addSql(
            'ALTER TABLE dlc_developer ADD CONSTRAINT FK_EEBD650BCEF6326C '
            . 'FOREIGN KEY (dlc_id) REFERENCES dlc (id) ON DELETE CASCADE',
        );
        $this->addSql(
            'ALTER TABLE dlc_developer ADD CONSTRAINT FK_EEBD650B64DD9267 '
            . 'FOREIGN KEY (developer_id) REFERENCES developer (id) ON DELETE CASCADE',
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE dlc_publisher (
                dlc_id INT NOT NULL,
                publisher_id INT NOT NULL,
                PRIMARY KEY(dlc_id, publisher_id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_17AE3BD7CEF6326C ON dlc_publisher (dlc_id)');
        $this->addSql('CREATE INDEX IDX_17AE3BD740C86FCE ON dlc_publisher (publisher_id)');
        $this->addSql(
            'ALTER TABLE dlc_publisher ADD CONSTRAINT FK_17AE3BD7CEF6326C '
            . 'FOREIGN KEY (dlc_id) REFERENCES dlc (id) ON DELETE CASCADE',
        );
        $this->addSql(
            'ALTER TABLE dlc_publisher ADD CONSTRAINT FK_17AE3BD740C86FCE '
            . 'FOREIGN KEY (publisher_id) REFERENCES publisher (id) ON DELETE CASCADE',
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE dlc_genre (
                dlc_id INT NOT NULL,
                genre_id INT NOT NULL,
                PRIMARY KEY(dlc_id, genre_id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_6236594DCEF6326C ON dlc_genre (dlc_id)');
        $this->addSql('CREATE INDEX IDX_6236594D4296D31F ON dlc_genre (genre_id)');
        $this->addSql(
            'ALTER TABLE dlc_genre ADD CONSTRAINT FK_6236594DCEF6326C '
            . 'FOREIGN KEY (dlc_id) REFERENCES dlc (id) ON DELETE CASCADE',
        );
        $this->addSql(
            'ALTER TABLE dlc_genre ADD CONSTRAINT FK_6236594D4296D31F '
            . 'FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE CASCADE',
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE dlc_platform (
                dlc_id INT NOT NULL,
                platform_id INT NOT NULL,
                PRIMARY KEY(dlc_id, platform_id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_C104AB91CEF6326C ON dlc_platform (dlc_id)');
        $this->addSql('CREATE INDEX IDX_C104AB91FFE6496F ON dlc_platform (platform_id)');
        $this->addSql(
            'ALTER TABLE dlc_platform ADD CONSTRAINT FK_C104AB91CEF6326C '
            . 'FOREIGN KEY (dlc_id) REFERENCES dlc (id) ON DELETE CASCADE',
        );
        $this->addSql(
            'ALTER TABLE dlc_platform ADD CONSTRAINT FK_C104AB91FFE6496F '
            . 'FOREIGN KEY (platform_id) REFERENCES platform (id) ON DELETE CASCADE',
        );

        // Тип appid (game/dlc/прочее) известен только после ответа appdetails —
        // на момент создания записи steam_game ни Game, ни Dlc ещё не существует.
        $this->addSql('ALTER TABLE steam_game ALTER game_id DROP NOT NULL');
        $this->addSql('ALTER TABLE steam_game ADD dlc_id INT DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EA3787B4CEF6326C ON steam_game (dlc_id)');
        $this->addSql(
            'ALTER TABLE steam_game ADD CONSTRAINT FK_EA3787B4CEF6326C '
            . 'FOREIGN KEY (dlc_id) REFERENCES dlc (id) NOT DEFERRABLE INITIALLY IMMEDIATE',
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE take (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                author_id INT NOT NULL,
                game_id INT NOT NULL,
                text VARCHAR(1000) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_TAKE_AUTHOR ON take (author_id)');
        $this->addSql('CREATE INDEX IDX_TAKE_GAME ON take (game_id)');
        $this->addSql(
            'ALTER TABLE take ADD CONSTRAINT FK_TAKE_AUTHOR '
            . 'FOREIGN KEY (author_id) REFERENCES "user" (id) ON DELETE CASCADE',
        );
        $this->addSql(
            'ALTER TABLE take ADD CONSTRAINT FK_TAKE_GAME '
            . 'FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE',
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE take_comment (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                take_id INT NOT NULL,
                author_id INT NOT NULL,
                text VARCHAR(1000) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_TAKE_COMMENT_TAKE ON take_comment (take_id)');
        $this->addSql('CREATE INDEX IDX_TAKE_COMMENT_AUTHOR ON take_comment (author_id)');
        $this->addSql(
            'ALTER TABLE take_comment ADD CONSTRAINT FK_TAKE_COMMENT_TAKE '
            . 'FOREIGN KEY (take_id) REFERENCES take (id) ON DELETE CASCADE',
        );
        $this->addSql(
            'ALTER TABLE take_comment ADD CONSTRAINT FK_TAKE_COMMENT_AUTHOR '
            . 'FOREIGN KEY (author_id) REFERENCES "user" (id) ON DELETE CASCADE',
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE take_reaction (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                take_id INT NOT NULL,
                user_id INT NOT NULL,
                type VARCHAR(10) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_TAKE_REACTION_TAKE_USER ON take_reaction (take_id, user_id)');
        $this->addSql('CREATE INDEX IDX_TAKE_REACTION_USER ON take_reaction (user_id)');
        $this->addSql(
            'ALTER TABLE take_reaction ADD CONSTRAINT FK_TAKE_REACTION_TAKE '
            . 'FOREIGN KEY (take_id) REFERENCES take (id) ON DELETE CASCADE',
        );
        $this->addSql(
            'ALTER TABLE take_reaction ADD CONSTRAINT FK_TAKE_REACTION_USER '
            . 'FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE',
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE take_reaction DROP CONSTRAINT FK_TAKE_REACTION_USER');
        $this->addSql('ALTER TABLE take_reaction DROP CONSTRAINT FK_TAKE_REACTION_TAKE');
        $this->addSql('DROP TABLE take_reaction');

        $this->addSql('ALTER TABLE take_comment DROP CONSTRAINT FK_TAKE_COMMENT_AUTHOR');
        $this->addSql('ALTER TABLE take_comment DROP CONSTRAINT FK_TAKE_COMMENT_TAKE');
        $this->addSql('DROP TABLE take_comment');

        $this->addSql('ALTER TABLE take DROP CONSTRAINT FK_TAKE_GAME');
        $this->addSql('ALTER TABLE take DROP CONSTRAINT FK_TAKE_AUTHOR');
        $this->addSql('DROP TABLE take');

        $this->addSql('ALTER TABLE steam_game DROP CONSTRAINT FK_EA3787B4CEF6326C');
        $this->addSql('DROP INDEX UNIQ_EA3787B4CEF6326C');
        $this->addSql('ALTER TABLE steam_game DROP dlc_id');
        $this->addSql('ALTER TABLE steam_game ALTER game_id SET NOT NULL');

        $this->addSql('DROP TABLE dlc_platform');
        $this->addSql('DROP TABLE dlc_genre');
        $this->addSql('DROP TABLE dlc_publisher');
        $this->addSql('DROP TABLE dlc_developer');
        $this->addSql('ALTER TABLE dlc DROP CONSTRAINT FK_AD6CAEA7E48FD905');
        $this->addSql('DROP TABLE dlc');

        $this->addSql('DROP TABLE cron');

        $this->addSql(<<<'SQL'
            ALTER TABLE "user"
                DROP nickname,
                DROP avatar_url,
                DROP last_login_at
        SQL);
    }
}
