<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260809142546 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial schema: game (+popularity), steam_game, steam_import_cursor, '
            . 'developer/publisher/genre/platform, user, cron_run, messenger_messages';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE game (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                name VARCHAR(255) NOT NULL,
                slug VARCHAR(255) NOT NULL,
                description TEXT DEFAULT NULL,
                release_date DATE DEFAULT NULL,
                cover_image_path VARCHAR(500) DEFAULT NULL,
                screenshot_urls JSON DEFAULT NULL,
                rating DOUBLE PRECISION DEFAULT NULL,
                metacritic_score INT DEFAULT NULL,
                popularity INT DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_232B318C989D9B62 ON game (slug)');

        $this->addSql(<<<'SQL'
            CREATE TABLE steam_game (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                game_id INT NOT NULL,
                steam_app_id INT NOT NULL,
                status VARCHAR(20) NOT NULL,
                raw_data JSON DEFAULT NULL,
                last_error TEXT DEFAULT NULL,
                attempts INT NOT NULL,
                fetched_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                last_attempt_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EA3787B44C1A4273 ON steam_game (steam_app_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EA3787B4E48FD905 ON steam_game (game_id)');
        $this->addSql(
            'ALTER TABLE steam_game ADD CONSTRAINT FK_EA3787B4E48FD905 '
            . 'FOREIGN KEY (game_id) REFERENCES game (id) NOT DEFERRABLE INITIALLY IMMEDIATE',
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE steam_import_cursor (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                last_app_id INT NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);

        $this->addSql(
            'CREATE TABLE developer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            . 'name VARCHAR(255) NOT NULL, PRIMARY KEY(id))',
        );
        $this->addSql('CREATE UNIQUE INDEX UNIQ_65FB8B9A5E237E06 ON developer (name)');

        $this->addSql(
            'CREATE TABLE publisher (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            . 'name VARCHAR(255) NOT NULL, PRIMARY KEY(id))',
        );
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9CE8D5465E237E06 ON publisher (name)');

        $this->addSql(
            'CREATE TABLE genre (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            . 'name VARCHAR(255) NOT NULL, PRIMARY KEY(id))',
        );
        $this->addSql('CREATE UNIQUE INDEX UNIQ_835033F85E237E06 ON genre (name)');

        $this->addSql(
            'CREATE TABLE platform (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            . 'name VARCHAR(50) NOT NULL, PRIMARY KEY(id))',
        );
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3952D0CB5E237E06 ON platform (name)');

        $this->addSql(<<<'SQL'
            CREATE TABLE game_developer (
                game_id INT NOT NULL,
                developer_id INT NOT NULL,
                PRIMARY KEY(game_id, developer_id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_B75D4A98E48FD905 ON game_developer (game_id)');
        $this->addSql('CREATE INDEX IDX_B75D4A9864DD9267 ON game_developer (developer_id)');
        $this->addSql(
            'ALTER TABLE game_developer ADD CONSTRAINT FK_B75D4A98E48FD905 '
            . 'FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE',
        );
        $this->addSql(
            'ALTER TABLE game_developer ADD CONSTRAINT FK_B75D4A9864DD9267 '
            . 'FOREIGN KEY (developer_id) REFERENCES developer (id) ON DELETE CASCADE',
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE game_publisher (
                game_id INT NOT NULL,
                publisher_id INT NOT NULL,
                PRIMARY KEY(game_id, publisher_id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_4E4E1444E48FD905 ON game_publisher (game_id)');
        $this->addSql('CREATE INDEX IDX_4E4E144440C86FCE ON game_publisher (publisher_id)');
        $this->addSql(
            'ALTER TABLE game_publisher ADD CONSTRAINT FK_4E4E1444E48FD905 '
            . 'FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE',
        );
        $this->addSql(
            'ALTER TABLE game_publisher ADD CONSTRAINT FK_4E4E144440C86FCE '
            . 'FOREIGN KEY (publisher_id) REFERENCES publisher (id) ON DELETE CASCADE',
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE game_genre (
                game_id INT NOT NULL,
                genre_id INT NOT NULL,
                PRIMARY KEY(game_id, genre_id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_B1634A77E48FD905 ON game_genre (game_id)');
        $this->addSql('CREATE INDEX IDX_B1634A774296D31F ON game_genre (genre_id)');
        $this->addSql(
            'ALTER TABLE game_genre ADD CONSTRAINT FK_B1634A77E48FD905 '
            . 'FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE',
        );
        $this->addSql(
            'ALTER TABLE game_genre ADD CONSTRAINT FK_B1634A774296D31F '
            . 'FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE CASCADE',
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE game_platform (
                game_id INT NOT NULL,
                platform_id INT NOT NULL,
                PRIMARY KEY(game_id, platform_id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_92162FEDE48FD905 ON game_platform (game_id)');
        $this->addSql('CREATE INDEX IDX_92162FEDFFE6496F ON game_platform (platform_id)');
        $this->addSql(
            'ALTER TABLE game_platform ADD CONSTRAINT FK_92162FEDE48FD905 '
            . 'FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE',
        );
        $this->addSql(
            'ALTER TABLE game_platform ADD CONSTRAINT FK_92162FEDFFE6496F '
            . 'FOREIGN KEY (platform_id) REFERENCES platform (id) ON DELETE CASCADE',
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE "user" (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                email VARCHAR(180) NOT NULL,
                password VARCHAR(255) NOT NULL,
                role VARCHAR(20) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');

        $this->addSql(<<<'SQL'
            CREATE TABLE cron_run (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                command VARCHAR(255) NOT NULL,
                arguments VARCHAR(1000) DEFAULT NULL,
                status VARCHAR(20) NOT NULL,
                started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                duration_ms INT DEFAULT NULL,
                memory_peak_bytes INT DEFAULT NULL,
                exit_code INT DEFAULT NULL,
                error_message TEXT DEFAULT NULL,
                log_path VARCHAR(500) DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_CRON_RUN_COMMAND ON cron_run (command)');
        $this->addSql('CREATE INDEX IDX_CRON_RUN_STARTED_AT ON cron_run (started_at)');
        $this->addSql('CREATE INDEX IDX_CRON_RUN_STATUS ON cron_run (status)');

        // symfony/messenger: doctrine-транспорт (MESSENGER_TRANSPORT_DSN=doctrine://default) —
        // таблица нужна бандлу, даже если очередь пока не используется приложением напрямую.
        $this->addSql(<<<'SQL'
            CREATE TABLE messenger_messages (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                body TEXT NOT NULL,
                headers TEXT NOT NULL,
                queue_name VARCHAR(190) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql(
            'CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 '
            . 'ON messenger_messages (queue_name, available_at, delivered_at, id)',
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('DROP TABLE cron_run');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE game_platform');
        $this->addSql('DROP TABLE game_genre');
        $this->addSql('DROP TABLE game_publisher');
        $this->addSql('DROP TABLE game_developer');
        $this->addSql('DROP TABLE platform');
        $this->addSql('DROP TABLE genre');
        $this->addSql('DROP TABLE publisher');
        $this->addSql('DROP TABLE developer');
        $this->addSql('DROP TABLE steam_import_cursor');
        $this->addSql('ALTER TABLE steam_game DROP CONSTRAINT FK_EA3787B4E48FD905');
        $this->addSql('DROP TABLE steam_game');
        $this->addSql('DROP TABLE game');
    }
}
