<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260813000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'audit_log: журнал действий (кто/когда/что/статус, произвольные детали в JSON)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE audit_log (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                user_id INT DEFAULT NULL,
                action VARCHAR(100) NOT NULL,
                status VARCHAR(10) NOT NULL,
                details JSON DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_AUDIT_LOG_ACTION ON audit_log (action)');
        $this->addSql('CREATE INDEX IDX_AUDIT_LOG_CREATED_AT ON audit_log (created_at)');
        $this->addSql('CREATE INDEX IDX_AUDIT_LOG_STATUS ON audit_log (status)');
        $this->addSql('CREATE INDEX IDX_AUDIT_LOG_USER ON audit_log (user_id)');
        $this->addSql(
            'ALTER TABLE audit_log ADD CONSTRAINT FK_AUDIT_LOG_USER '
            . 'FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL',
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE audit_log');
    }
}
