<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260811150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'our_game (+our_game_genre, our_game_download_link) — игры собственной разработки для продвижения на сайте';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE our_game (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                name VARCHAR(255) NOT NULL,
                slug VARCHAR(255) NOT NULL,
                description TEXT DEFAULT NULL,
                status VARCHAR(20) NOT NULL,
                current_version VARCHAR(50) DEFAULT NULL,
                release_date DATE DEFAULT NULL,
                version_updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                trailer_url VARCHAR(500) DEFAULT NULL,
                cover_image_path VARCHAR(500) DEFAULT NULL,
                banner_image_path VARCHAR(500) DEFAULT NULL,
                screenshot_urls JSON DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_OUR_GAME_SLUG ON our_game (slug)');

        $this->addSql(<<<'SQL'
            CREATE TABLE our_game_genre (
                our_game_id INT NOT NULL,
                genre_id INT NOT NULL,
                PRIMARY KEY(our_game_id, genre_id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_OUR_GAME_GENRE_OUR_GAME ON our_game_genre (our_game_id)');
        $this->addSql('CREATE INDEX IDX_OUR_GAME_GENRE_GENRE ON our_game_genre (genre_id)');
        $this->addSql(
            'ALTER TABLE our_game_genre ADD CONSTRAINT FK_OUR_GAME_GENRE_OUR_GAME '
            . 'FOREIGN KEY (our_game_id) REFERENCES our_game (id) ON DELETE CASCADE',
        );
        $this->addSql(
            'ALTER TABLE our_game_genre ADD CONSTRAINT FK_OUR_GAME_GENRE_GENRE '
            . 'FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE CASCADE',
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE our_game_download_link (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                our_game_id INT NOT NULL,
                platform VARCHAR(20) NOT NULL,
                url VARCHAR(500) NOT NULL,
                image_path VARCHAR(500) DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_OUR_GAME_DOWNLOAD_LINK_OUR_GAME ON our_game_download_link (our_game_id)');
        $this->addSql(
            'ALTER TABLE our_game_download_link ADD CONSTRAINT FK_OUR_GAME_DOWNLOAD_LINK_OUR_GAME '
            . 'FOREIGN KEY (our_game_id) REFERENCES our_game (id) ON DELETE CASCADE',
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE our_game_download_link DROP CONSTRAINT FK_OUR_GAME_DOWNLOAD_LINK_OUR_GAME');
        $this->addSql('DROP TABLE our_game_download_link');

        $this->addSql('ALTER TABLE our_game_genre DROP CONSTRAINT FK_OUR_GAME_GENRE_GENRE');
        $this->addSql('ALTER TABLE our_game_genre DROP CONSTRAINT FK_OUR_GAME_GENRE_OUR_GAME');
        $this->addSql('DROP TABLE our_game_genre');

        $this->addSql('DROP TABLE our_game');
    }
}
