<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260916090000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Импорт наличия игр на ggsel.net: ggsel_game — факт наличия и ссылка на товар; '
            . 'ggsel_import_cursor — курсор пачечного обхода по убыванию популярности игры';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE ggsel_game (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                game_id INT NOT NULL,
                url VARCHAR(500) NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_GGSEL_GAME_GAME ON ggsel_game (game_id)');
        $this->addSql(
            'ALTER TABLE ggsel_game ADD CONSTRAINT FK_GGSEL_GAME_GAME '
            . 'FOREIGN KEY (game_id) REFERENCES game (id) ON DELETE CASCADE',
        );

        $this->addSql(<<<'SQL'
            CREATE TABLE ggsel_import_cursor (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                last_popularity INT DEFAULT NULL,
                last_game_id INT NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE ggsel_import_cursor');
        $this->addSql('ALTER TABLE ggsel_game DROP CONSTRAINT FK_GGSEL_GAME_GAME');
        $this->addSql('DROP TABLE ggsel_game');
    }
}
