<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260812120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'our_game_post — посты об играх собственной разработки (анонсы, обновления)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE our_game_post (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                game_id INT NOT NULL,
                author_id INT NOT NULL,
                type VARCHAR(20) NOT NULL,
                status VARCHAR(20) NOT NULL,
                posted_at DATE NOT NULL,
                image_path VARCHAR(500) DEFAULT NULL,
                short_description VARCHAR(500) NOT NULL,
                full_description TEXT DEFAULT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_OUR_GAME_POST_GAME ON our_game_post (game_id)');
        $this->addSql('CREATE INDEX IDX_OUR_GAME_POST_AUTHOR ON our_game_post (author_id)');
        $this->addSql(
            'ALTER TABLE our_game_post ADD CONSTRAINT FK_OUR_GAME_POST_GAME '
            . 'FOREIGN KEY (game_id) REFERENCES our_game (id) ON DELETE CASCADE',
        );
        $this->addSql(
            'ALTER TABLE our_game_post ADD CONSTRAINT FK_OUR_GAME_POST_AUTHOR '
            . 'FOREIGN KEY (author_id) REFERENCES "user" (id) ON DELETE CASCADE',
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE our_game_post DROP CONSTRAINT FK_OUR_GAME_POST_AUTHOR');
        $this->addSql('ALTER TABLE our_game_post DROP CONSTRAINT FK_OUR_GAME_POST_GAME');
        $this->addSql('DROP TABLE our_game_post');
    }
}
