name: Network Test for Taiga

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test network connectivity
        env:
          TAIGA_USERNAME: gjhonic
          TAIGA_PASSWORD: ${{ secrets.TAIGA_PASSWORD }}
        run: |
          echo "=== Testing network connectivity to Taiga ==="
          
          # Test basic connectivity
          echo "1. Testing basic connectivity..."
          if curl -s --connect-timeout 10 --max-time 30 "https://api.taiga.io/api/v1/" > /dev/null; then
            echo "✅ api.taiga.io is reachable"
          else
            echo "❌ api.taiga.io is not reachable"
          fi
          
          if curl -s --connect-timeout 10 --max-time 30 "https://tree.taiga.io/api/v1/" > /dev/null; then
            echo "✅ tree.taiga.io is reachable"
          else
            echo "❌ tree.taiga.io is not reachable"
          fi
          
          if curl -s --connect-timeout 10 --max-time 30 "https://taiga.io/api/v1/" > /dev/null; then
            echo "✅ taiga.io is reachable"
          else
            echo "❌ taiga.io is not reachable"
          fi
          
          echo ""
          echo "2. Testing authentication with timeouts..."
          
          # Test auth with proper timeouts
          echo "=== Testing api.taiga.io auth ==="
          RESPONSE1=$(curl -s --connect-timeout 10 --max-time 30 -X POST "https://api.taiga.io/api/v1/auth" \
            -H "Content-Type: application/json" \
            -d '{"type":"normal","username":"'$TAIGA_USERNAME'","password":"'$TAIGA_PASSWORD'"}')
          
          if [ $? -eq 0 ]; then
            echo "✅ Request successful"
            echo "Response: $RESPONSE1"
            if echo "$RESPONSE1" | jq -e '.auth_token' > /dev/null 2>&1; then
              echo "✅ Authentication successful!"
            else
              echo "❌ Authentication failed: $RESPONSE1"
            fi
          else
            echo "❌ Request failed with curl error code: $?"
          fi
          
          echo ""
          echo "=== Testing tree.taiga.io auth ==="
          RESPONSE2=$(curl -s --connect-timeout 10 --max-time 30 -X POST "https://tree.taiga.io/api/v1/auth" \
            -H "Content-Type: application/json" \
            -d '{"type":"normal","username":"'$TAIGA_USERNAME'","password":"'$TAIGA_PASSWORD'"}')
          
          if [ $? -eq 0 ]; then
            echo "✅ Request successful"
            echo "Response: $RESPONSE2"
            if echo "$RESPONSE2" | jq -e '.auth_token' > /dev/null 2>&1; then
              echo "✅ Authentication successful!"
            else
              echo "❌ Authentication failed: $RESPONSE2"
            fi
          else
            echo "❌ Request failed with curl error code: $?"
          fi
          
          echo ""
          echo "=== Testing taiga.io auth ==="
          RESPONSE3=$(curl -s --connect-timeout 10 --max-time 30 -X POST "https://taiga.io/api/v1/auth" \
            -H "Content-Type: application/json" \
            -d '{"type":"normal","username":"'$TAIGA_USERNAME'","password":"'$TAIGA_PASSWORD'"}')
          
          if [ $? -eq 0 ]; then
            echo "✅ Request successful"
            echo "Response: $RESPONSE3"
            if echo "$RESPONSE3" | jq -e '.auth_token' > /dev/null 2>&1; then
              echo "✅ Authentication successful!"
            else
              echo "❌ Authentication failed: $RESPONSE3"
            fi
          else
            echo "❌ Request failed with curl error code: $?"
          fi
          
          echo ""
          echo "=== Summary ==="
          echo "If all requests failed with network errors, there might be:"
          echo "1. Network connectivity issues from GitHub Actions"
          echo "2. Firewall blocking connections"
          echo "3. DNS resolution problems"
          echo "4. Taiga API servers temporarily unavailable" 
