name: Debug Taiga Authentication (Main)

on:
  workflow_dispatch:

env:
  TAIGA_API: https://api.taiga.io/api/v1
  TAIGA_USERNAME: gjhonic

jobs:
  debug-auth:
    runs-on: ubuntu-latest

    steps:
      - name: Test different authentication methods
        env:
          TAIGA_USERNAME: ${{ env.TAIGA_USERNAME }}
          TAIGA_PASSWORD: ${{ secrets.TAIGA_PASSWORD }}
          TAIGA_API: ${{ env.TAIGA_API }}
        run: |
          echo "=== Debugging Taiga Authentication ==="
          echo "Username: $TAIGA_USERNAME"
          echo "Password length: ${#TAIGA_PASSWORD}"
          echo "API: $TAIGA_API"
          echo ""
          
          # Method 1: Direct string (like Postman)
          echo "=== Method 1: Direct string ==="
          AUTH_PAYLOAD_1='{"type":"normal","username":"'$TAIGA_USERNAME'","password":"'$TAIGA_PASSWORD'"}'
          echo "Payload 1: $AUTH_PAYLOAD_1"
          
          RESPONSE_1=$(curl -s -w "%{http_code}" -X POST "$TAIGA_API/auth" \
            -H "Content-Type: application/json" \
            -d "$AUTH_PAYLOAD_1")
          
          HTTP_CODE_1="${RESPONSE_1: -3}"
          BODY_1="${RESPONSE_1%???}"
          echo "HTTP Code 1: $HTTP_CODE_1"
          echo "Response 1: $BODY_1"
          echo ""
          
          # Method 2: Using jq
          echo "=== Method 2: Using jq ==="
          AUTH_PAYLOAD_2=$(jq -n \
            --arg username "$TAIGA_USERNAME" \
            --arg password "$TAIGA_PASSWORD" \
            '{type: "normal", username: $username, password: $password}')
          echo "Payload 2: $AUTH_PAYLOAD_2"
          
          RESPONSE_2=$(curl -s -w "%{http_code}" -X POST "$TAIGA_API/auth" \
            -H "Content-Type: application/json" \
            -d "$AUTH_PAYLOAD_2")
          
          HTTP_CODE_2="${RESPONSE_2: -3}"
          BODY_2="${RESPONSE_2%???}"
          echo "HTTP Code 2: $HTTP_CODE_2"
          echo "Response 2: $BODY_2"
          echo ""
          
          # Method 3: Using printf
          echo "=== Method 3: Using printf ==="
          AUTH_PAYLOAD_3=$(printf '{"type":"normal","username":"%s","password":"%s"}' "$TAIGA_USERNAME" "$TAIGA_PASSWORD")
          echo "Payload 3: $AUTH_PAYLOAD_3"
          
          RESPONSE_3=$(curl -s -w "%{http_code}" -X POST "$TAIGA_API/auth" \
            -H "Content-Type: application/json" \
            -d "$AUTH_PAYLOAD_3")
          
          HTTP_CODE_3="${RESPONSE_3: -3}"
          BODY_3="${RESPONSE_3%???}"
          echo "HTTP Code 3: $HTTP_CODE_3"
          echo "Response 3: $BODY_3"
          echo ""
          
          # Check if any method worked
          if [[ "$HTTP_CODE_1" == "200" ]]; then
            echo "✅ Method 1 worked!"
            TOKEN=$(echo "$BODY_1" | jq -r '.auth_token')
            echo "Token: ${TOKEN:0:20}..."
          elif [[ "$HTTP_CODE_2" == "200" ]]; then
            echo "✅ Method 2 worked!"
            TOKEN=$(echo "$BODY_2" | jq -r '.auth_token')
            echo "Token: ${TOKEN:0:20}..."
          elif [[ "$HTTP_CODE_3" == "200" ]]; then
            echo "✅ Method 3 worked!"
            TOKEN=$(echo "$BODY_3" | jq -r '.auth_token')
            echo "Token: ${TOKEN:0:20}..."
          else
            echo "❌ All methods failed"
            echo "Possible issues:"
            echo "1. Wrong username/password"
            echo "2. Account not active"
            echo "3. API endpoint issue"
            echo "4. Network/connectivity issue"
          fi
          
          # Test API accessibility
          echo ""
          echo "=== Testing API accessibility ==="
          API_TEST=$(curl -s -w "%{http_code}" "$TAIGA_API/")
          API_HTTP_CODE="${API_TEST: -3}"
          API_BODY="${API_TEST%???}"
          echo "API HTTP Code: $API_HTTP_CODE"
          echo "API Response: $API_BODY" 
